# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

env:
  SH_FILES:
    sh: find . -type f -name '*.sh'

tasks:
  format:
    cmds:
      - shfmt --indent 2 --space-redirects --simplify --write $SH_FILES
      - chmod +x $SH_FILES

  lint:
    cmds:
      - shellcheck $SH_FILES

  build:
    cmds:
      - docker build . --tag arranhs/closedagent:latest

  run:
    cmds:
      - docker compose up

  connect:
    cmds:
      - docker exec -it closedagent /bin/bash
