name: Build and Push closedagent Image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-closedagent.yaml
      - .github/workflows/build.yaml
      - images/closedagent/**
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
    inputs:
      no-cache:
        description: No Cache
        type: boolean
        default: false

jobs:
  get-tags:
    name: Get Tags
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      tags: ${{ steps.get-tags.outputs.tags }}

    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v6

      - name: Get tags
        id: get-tags
        run: |
          CALVER=$(date -u +"%Y.%m.%d")

          {
            echo "tags<<EOF"
            echo "latest"
            echo "$CALVER"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

          echo "
          Output:
          tags: latest, $CALVER
          "

  build:
    name: Build Image
    uses: ./.github/workflows/build.yaml
    needs: get-tags
    with:
      image-name: arranhs/closedagent
      context-path: images/closedagent
      image-tags: ${{ needs.get-tags.outputs.tags }}
    secrets: inherit
