name: Build and Push openchamber Image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-openchamber.yaml
      - .github/workflows/update-openchamber.yaml
      - .github/workflows/build.yaml
      - images/openchamber/**
  schedule:
    - cron: 0 3 * * *  # Everyday at 3am
  workflow_dispatch:
    inputs:
      no-cache:
        description: No Cache
        type: boolean
        default: false

jobs:
  get-tags:
    name: Get Tags
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      tags: ${{ steps.get-tags.outputs.tags }}

    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v6

      - name: Get tags
        id: get-tags
        run: |
          OPENCHAMBER_VERSION=$(
            grep "^ARG OPENCHAMBER_VERSION=" images/openchamber/Dockerfile | 
            cut -d '=' -f2
          )

          {
            echo "tags<<EOF"
            echo "latest"
            echo "$OPENCHAMBER_VERSION"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
  
          echo "
          Output:
          tags: latest, $OPENCHAMBER_VERSION
          "

  build:
    name: Build Image
    needs: get-tags
    uses: ./.github/workflows/build.yaml
    with:
      image-name: arranhs/openchamber
      context-path: images/openchamber
      image-tags: ${{ needs.get-tags.outputs.tags }}
    secrets: inherit
