name: Update paseo version

on:
  schedule:
    - cron: 0 2 * * * # Everyday at 2am
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: Update version
    uses: ahobsonsayers/github-workflows/.github/workflows/docker-update-app-version.yaml@main
    with:
      app-name: Paseo
      dockerfile: images/paseo/Dockerfile
      version-arg: PASEO_VERSION
      version-source: npm
      version-source-npm-package: "@getpaseo/cli"
