name: Update opencode version

on:
  schedule:
    - cron: 0 1 * * * # Everyday at 1am
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: Update version
    uses: ./.github/workflows/update.yaml
    with:
      app-name: OpenCode
      dockerfile: images/opencode/Dockerfile
      version-arg: OPENCODE_VERSION
      version-source: npm
      version-source-npm-package: opencode-ai
