name: Update hermes version

on:
  schedule:
    - cron: 0 1 * * * # Everyday at 1am
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: Update version
    uses: ./.github/workflows/update.yaml
    with:
      app-name: Hermes
      dockerfile: images/hermes/Dockerfile
      version-arg: HERMES_VERSION
      version-source: github
      version-source-github-repo: NousResearch/hermes-agent
