name: Update openchamber version

on:
  schedule:
    - cron: 0 2 * * * # Everyday at 2am
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: Update version
    uses: ahobsonsayers/github-workflows/.github/workflows/docker-update-app-version.yaml@main
    with:
      app-name: OpenChamber
      dockerfile: images/openchamber/Dockerfile
      version-arg: OPENCHAMBER_VERSION
      version-source: npm
      version-source-npm-package: "@openchamber/web"
